### ISSUE TITLE
Security Error in Chrome

### ISSUE THREAD

**Issue by jamesjpk123** [marblelympics/marblelympics.github.io#18]
I have an error with the new site at www.marblelympics.com (great domain name by the way!). It gives me a privacy warning, 
![capture](https://user-images.githubusercontent.com/18013689/29008811-3c0cf1e6-7ada-11e7-9cab-7716ce78fa0f.PNG)
![capture](https://user-images.githubusercontent.com/18013689/29008829-74ef4a54-7ada-11e7-9554-eb0e0d098518.PNG)

**Comment by rrraptor** [comment]
It should work fine except you're using https instead of http. I'm no longer able to use ssl with the new site as it's hosted by github pages and they're automating ssl via lets-encrypt. For custom domains, they haven't implemented a clean way to enabled zero or near-zero infra automated ssl. I have no interest in setting up a Cloudflare proxy.

For reference https://github.com/isaacs/github/issues/156
