### ISSUE TITLE
Community Instagram + Twitter #hashtag Integration.

### ISSUE THREAD

**Issue by jamesjpk123** [marblelympics/marblelympics.github.io#22]
Hey! I was wondering if you could somehow implement [this codepen](https://codepen.io/jamesjpk123/pen/KZNPma) into the main page! I think it would be so cool to show the newest posts on the #marblelympics hashtag on Instagram + Twitter to let people know what's happening. Right now, the attribute `data-per="3"` on the `<ul>` tag controls how many posts are shown on load. Also, the CSS controls how big it is, and how it is centered. Get back to me if you think this is a plausible idea.

**Comment by rrraptor** [comment]
Currently, there's no third party UI code on the site, just plain html and javascript.

I don't really like the idea of putting third part code in, especially since Juicer adds referral links and their own advertisements in the free plan. I'll brew on it, but probably not interested unless it's official widget code from Twitter or Instagram.

Twitter and Instagram used to have a simple url scheme or rss for embedding content, but now you need an account with API access to do so. I don't have an account on either, so probably not going to take that route.

**Comment by jamesjpk123** [comment]
Yeah, they have made it super complicated, and they even have a "review" process. I hate how they just made extra hurdles. It just slows development, and doesn't help the developer.
